### ISSUE TITLE
Still depends on specification.xml files

### ISSUE THREAD

**Issue by thomwiggers** [privacybydesign/credentials_idemix#3]
The irma_web_service verifiers rely on `specification.xml` files in `irma_configuration` through this project, but those were removed a [long time ago](https://github.com/credentials/irma_configuration/commit/441c31399d3adea5d9f5854556a286680de1462a).

**Comment by wouterl** [comment]
This might be old code, can you tell me where you found this?

**Comment by thomwiggers** [comment]
e.g. https://github.com/credentials/credentials_idemix/blob/master/src/org/irmacard/credentials/idemix/util/VerifyCredentialInformation.java#L49

**Comment by wouterl** [comment]
Thx for the pointer. However, this file is never referenced (at least not
in this location, I'm assuming you ran into a problem somewhere though,
so there might be a bug elsewhere). Instead, what you see in this line is
just a label. This label is used by the underlying library.

Did you run into an actual problem with specification.xml?

Detailed explation.

The actual specification.xml file is generated on the fly when
`getIdemixVerifySpecification()` is called using the
`IdemixVerificationStructureCreator`, and then loaded using `init()`.
That is why things work, even though this file actually doesn't exist.

**Comment by thomwiggers** [comment]
`irma_web_service` definitely relies on this part of the `credentials_idemix` API. Adding a specification.xml for irmaTube fixed verification that would otherwise just result in a `NullPointerException`.

**Comment by wouterl** [comment]
Ok, so there is indeed a problem somewhere, but as far as I can see, the
specification.xml should be generated on the fly in this part of the API.

Do you perhaps have a trace of the NullPointerException? Or instructions
for how to reproduce?
